// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQzbxVvk7yRk-wbyTlFRoumE6WdRTSrk',
    appId: '1:215043806402:web:47003284f3997a28dc175b',
    messagingSenderId: '215043806402',
    projectId: 'travelapp-df5a3',
    authDomain: 'travelapp-df5a3.firebaseapp.com',
    storageBucket: 'travelapp-df5a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpDp0BXRQBd8kbZ9ZtTAkhzWTIFra1SDQ',
    appId: '1:215043806402:android:cb7e6de1bc536e53dc175b',
    messagingSenderId: '215043806402',
    projectId: 'travelapp-df5a3',
    storageBucket: 'travelapp-df5a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFPfDQUqe9P_ninq0ldHeM2NITlbPNtgU',
    appId: '1:215043806402:ios:18425d4d1c3132f9dc175b',
    messagingSenderId: '215043806402',
    projectId: 'travelapp-df5a3',
    storageBucket: 'travelapp-df5a3.appspot.com',
    iosBundleId: 'com.viskav.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFPfDQUqe9P_ninq0ldHeM2NITlbPNtgU',
    appId: '1:215043806402:ios:f00a12abf481c8fbdc175b',
    messagingSenderId: '215043806402',
    projectId: 'travelapp-df5a3',
    storageBucket: 'travelapp-df5a3.appspot.com',
    iosBundleId: 'com.viskav.travel.RunnerTests',
  );
}
